### ISSUE TITLE
Sometimes snippet contains gibberish

### ISSUE THREAD

**Issue by maxgoedjen** [maxgoedjen/xray#3]
Might be base64 encode/decode going wrong?

**Comment by maxgoedjen** [comment]
<img width="1431" alt="image" src="https://user-images.githubusercontent.com/342665/108324947-65574180-717d-11eb-83f0-215c498b2de9.png">

URL in that case is 
```
https://ray.so?code=ZnVuYyBwaWRBbmROYW1lSW5mbyhmcm9tIHBpZDogSW50MzIpIC0+IGtpbmZvX3Byb2MgewogICAgICAgIHZhciBsZW4gPSBNZW1vcnlMYXlvdXQ8a2luZm9fcHJvYz4uc2l6ZQogICAgICAgIGxldCBpbmZvUG9pbnRlciA9IFVuc2FmZU11dGFibGVSYXdQb2ludGVyLmFsbG9jYXRlKGJ5dGVDb3VudDogbGVuLCBhbGlnbm1lbnQ6IDEpCiAgICAgICAgdmFyIG5hbWU6IFtJbnQzMl0gPSBbQ1RMX0tFUk4sIEtFUk5fUFJPQywgS0VSTl9QUk9DX1BJRCwgcGlkXQogICAgICAgIHN5c2N0bCgmbmFtZSwgVUludDMyKG5hbWUuY291bnQpLCBpbmZvUG9pbnRlciwgJmxlbiwgbmlsLCAwKQogICAgICAgIHJldHVybiBpbmZvUG9pbnRlci5sb2FkKGFzOiBraW5mb19wcm9jLnNlbGYpCiAgICB9&colors=midnight&background=true&darkMode=true&padding=32```

Which _seems_ to be valid base64?

**Comment by thomaspaulmann** [comment]
We had a similar issue for the [script command](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/create-image-from-code.sh#L37). You should URL encode the Base64 code because `+` is a valid base64 character but makes trouble in URLs. I hope that helps :-)
